const TOTAL=604;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let state=JSON.parse(localStorage.getItem('khatm-state')||'null')||{days:30,start:new Date().toISOString().slice(0,10),completed:0,done:[],mode:'prayers',lang:'ar',dark:false};const save=()=>localStorage.setItem('khatm-state',JSON.stringify(state));
const tr={ar:{brand:'اختم قرآنك',tag:'رفيقك لإتمام كتاب الله',today:'اختم قرآنك بـ 30 يومًا',hero:'كل يوم خطوة، حتى تتم الختمة.',heroSub:'خطة هادئة ومرنة تقسم وردك وتعيد توزيعه إذا فاتك يوم.',progress:'الإنجاز',day:'اليوم',remaining:'المتبقي',plan:'الخطة',daily:'ورد اليوم',continue:'تابع ختمتك',nextPrayer:'الصلاة القادمة',locationPrivacy:'لن نطلب موقعك إلا عند استخدام الصلاة أو القبلة.',useLocation:'استخدم موقعي',privacyFirst:'الخصوصية أولًا',noAccount:'لا تحتاج حسابًا',localData:'تقدمك وإعداداتك تحفظ على جهازك في هذه النسخة.',quran:'القرآن',reader:'قارئ هادئ وواضح',verses:'الآيات',mushaf:'المصحف',surah:'السورة',sourceNotice:'النص القرآني سيُربط بمصدر موثّق؛ لا نعرض نصًا تجريبيًا على أنه قرآن.',readerReady:'واجهة القارئ جاهزة لربط المصدر المعتمد والترجمات والتلاوات.',khatm:'ختمتي',buildPlan:'ابنِ ختمتك كما تناسب يومك',duration:'مدة الختمة',distribution:'توزيع الورد',dailyAvg:'المتوسط اليومي',startPlan:'ابدأ الختمة',prayer:'الصلاة',prayerQibla:'المواقيت والقبلة',prayerTimes:'مواقيت الصلاة',permission:'نطلب الموقع فقط بعد موافقتك. يمكن إضافة اختيار المدينة يدويًا عند ربط خدمة المواقيت.',qibla:'القبلة',sensor:'إذا لم يوفر الجهاز مستشعرًا موثوقًا، نعرض الاتجاه بالنسبة للشمال فقط.',more:'المزيد',settings:'إعدادات ومعلومات المشروع',languages:'اللغات والترجمات',backup:'تصدير واستيراد البيانات',sources:'المصادر',privacy:'الخصوصية',about:'حول اختم قرآنك',home:'الرئيسية'},en:{brand:'Khatm Quran',tag:'Your companion to complete the Quran',today:'Complete the Quran in 30 Days',hero:'One step every day, until you complete it.',heroSub:'A calm, flexible plan that redistributes your reading if you miss a day.',progress:'Progress',day:'Day',remaining:'Remaining',plan:'Plan',daily:'Today’s reading',continue:'Continue Khatm',nextPrayer:'Next prayer',locationPrivacy:'Location is requested only for prayer times or Qibla.',useLocation:'Use my location',privacyFirst:'Privacy first',noAccount:'No account required',localData:'Progress and settings stay on your device in this version.',quran:'Quran',reader:'A calm, clear reader',verses:'Verses',mushaf:'Mushaf',surah:'Surah',sourceNotice:'Quran text will be connected to a verified source; placeholder text is never presented as Quran.',readerReady:'Reader UI is ready for verified Quran text, translations and recitations.',khatm:'My Khatm',buildPlan:'Build a Khatm around your day',duration:'Khatm duration',distribution:'Reading distribution',dailyAvg:'Daily average',startPlan:'Start Khatm',prayer:'Prayer',prayerQibla:'Prayer times & Qibla',prayerTimes:'Prayer times',permission:'Location is requested only with your permission. Manual city selection can be added with the prayer service.',qibla:'Qibla',sensor:'If a reliable sensor is unavailable, direction is shown relative to north only.',more:'More',settings:'Settings & project information',languages:'Languages & translations',backup:'Export & import data',sources:'Sources',privacy:'Privacy',about:'About Khatm Quran',home:'Home'}};
function applyLang(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(e=>e.textContent=tr[state.lang][e.dataset.i18n]||e.textContent);$('#langBtn').textContent=state.lang==='ar'?'EN':'ع';render()}
$('#langBtn').onclick=()=>{state.lang=state.lang==='ar'?'en':'ar';save();applyLang()};$('#themeBtn').onclick=()=>{state.dark=!state.dark;document.body.classList.toggle('dark',state.dark);save()};document.body.classList.toggle('dark',state.dark);
const prayerNames={ar:['الفجر','الظهر','العصر','المغرب','العشاء'],en:['Fajr','Dhuhr','Asr','Maghrib','Isha']};
function render(){let pct=Math.round(state.completed/TOTAL*100);$('#percent').textContent=pct+'%';$('#remaining').textContent=(TOTAL-state.completed)+(state.lang==='ar'?' صفحة':' pages');$('#planLabel').textContent=state.days+(state.lang==='ar'?' يومًا':' days');let elapsed=Math.max(1,Math.floor((new Date()-new Date(state.start+'T00:00:00'))/864e5)+1);$('#dayNow').textContent=Math.min(elapsed,state.days)+' / '+state.days;let daily=Math.ceil((TOTAL-state.completed)/Math.max(1,state.days-elapsed+1));let start=state.completed+1,end=Math.min(TOTAL,state.completed+daily);$('#dailyPages').textContent=state.lang==='ar'?('الصفحات '+start+'–'+end):('Pages '+start+'–'+end);let parts=state.mode==='prayers'?5:state.mode==='three'?3:1;let names=state.mode==='prayers'?prayerNames[state.lang]:(state.mode==='three'?(state.lang==='ar'?['صباحًا','ظهرًا','مساءً']:['Morning','Noon','Evening']):(state.lang==='ar'?['جلسة اليوم']:['Daily session']));$('#sessions').innerHTML=names.map((n,i)=>{let a=start+Math.floor(daily/parts*i),b=i===parts-1?end:Math.min(end,start+Math.floor(daily/parts*(i+1))-1),done=state.done.includes(i);return '<button class="session '+(done?'done':'')+'" data-i="'+i+'"><b>'+n+'</b><small>'+a+'–'+b+'</small></button>'}).join('');$$('.session').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;if(state.done.includes(i))state.done=state.done.filter(x=>x!==i);else state.done.push(i);if(state.done.length===parts){state.completed=Math.min(TOTAL,end);state.done=[]}save();render()});$('#avgPages').textContent=Math.ceil(TOTAL/state.days)+(state.lang==='ar'?' صفحة':' pages')}
$$('#nav button').forEach(b=>b.onclick=()=>{$$('.page').forEach(p=>p.classList.remove('active'));$('#'+b.dataset.page).classList.add('active');$$('#nav button').forEach(x=>x.classList.toggle('active',x===b));scrollTo(0,0)});
const plans=[7,10,15,20,30,40,60,90];$('#plans').innerHTML=plans.map(d=>'<button data-d="'+d+'" class="'+(d===state.days?'selected':'')+'">'+d+'</button>').join('');$$('#plans button').forEach(b=>b.onclick=()=>{$$('#plans button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.days=+b.dataset.d;render()});
const modes=[['prayers','5 صلوات','5 prayers'],['three','3 فترات','3 periods'],['once','جلسة واحدة','One session']];function renderModes(){$('#modes').innerHTML=modes.map(m=>'<button data-m="'+m[0]+'" class="'+(m[0]===state.mode?'selected':'')+'">'+m[state.lang==='ar'?1:2]+'</button>').join('');$$('#modes button').forEach(b=>b.onclick=()=>{state.mode=b.dataset.m;renderModes();render()})}renderModes();$('#startPlan').onclick=()=>{state.start=new Date().toISOString().slice(0,10);state.completed=0;state.done=[];save();render();$$('#nav button')[0].click()};
const surahs=['الفاتحة','البقرة','آل عمران','النساء','المائدة','الأنعام','الأعراف','الأنفال','التوبة','يونس','هود','يوسف','الرعد','إبراهيم','الحجر','النحل','الإسراء','الكهف','مريم','طه','الأنبياء','الحج','المؤمنون','النور','الفرقان','الشعراء','النمل','القصص','العنكبوت','الروم','لقمان','السجدة','الأحزاب','سبأ','فاطر','يس','الصافات','ص','الزمر','غافر','فصلت','الشورى','الزخرف','الدخان','الجاثية','الأحقاف','محمد','الفتح','الحجرات','ق','الذاريات','الطور','النجم','القمر','الرحمن','الواقعة','الحديد','المجادلة','الحشر','الممتحنة','الصف','الجمعة','المنافقون','التغابن','الطلاق','التحريم','الملك','القلم','الحاقة','المعارج','نوح','الجن','المزمل','المدثر','القيامة','الإنسان','المرسلات','النبأ','النازعات','عبس','التكوير','الانفطار','المطففين','الانشقاق','البروج','الطارق','الأعلى','الغاشية','الفجر','البلد','الشمس','الليل','الضحى','الشرح','التين','العلق','القدر','البينة','الزلزلة','العاديات','القارعة','التكاثر','العصر','الهمزة','الفيل','قريش','الماعون','الكوثر','الكافرون','النصر','المسد','الإخلاص','الفلق','الناس'];$('#surahSelect').innerHTML=surahs.map((s,i)=>'<option>'+(i+1)+'. '+s+'</option>').join('');
function qibla(lat,lon){const kaaba=[21.4225,39.8262],r=x=>x*Math.PI/180,d=x=>x*180/Math.PI;let y=Math.sin(r(kaaba[1]-lon))*Math.cos(r(kaaba[0])),x=Math.cos(r(lat))*Math.sin(r(kaaba[0]))-Math.sin(r(lat))*Math.cos(r(kaaba[0]))*Math.cos(r(kaaba[1]-lon));return(d(Math.atan2(y,x))+360)%360}
function locate(){if(!navigator.geolocation){$('#prayerStatus').textContent='Geolocation unavailable';return}navigator.geolocation.getCurrentPosition(p=>{let deg=qibla(p.coords.latitude,p.coords.longitude);$('#qiblaDegrees').textContent=Math.round(deg)+'°';$('#needle').style.transform='rotate('+deg+'deg)';$('#nextPrayer').textContent=state.lang==='ar'?'تم تحديد موقعك — ربط المواقيت الموثقة هو الخطوة التالية':'Location set — verified prayer service connection is next';$('#prayerStatus').textContent=state.lang==='ar'?'تم تحديد الموقع. لا يتم حفظ إحداثياتك في ملف الختمة.':'Location acquired. Coordinates are not stored in your Khatm data.'},()=>{$('#prayerStatus').textContent=state.lang==='ar'?'لم يتم منح إذن الموقع.':'Location permission was not granted.'})}$('#locateBtn').onclick=locate;$('#prayerLocate').onclick=locate;
const modal=$('#modal');$('.close').onclick=()=>modal.close();const modalText={about:'<h2>اختم قرآنك</h2><p>منصة مجانية وبدون إعلانات لمساعدة المسلمين على قراءة القرآن وإتمام الختمة.</p><p><b>صدقة جارية عن محمد العقلة وعائلته.</b></p>',privacy:'<h2>الخصوصية</h2><p>لا يلزم حساب للاستخدام الأساسي. تحفظ بيانات الختمة والإعدادات محليًا. الموقع الجغرافي لا يطلب إلا عند اختيار خدمات الصلاة أو القبلة.</p>',sources:'<h2>المصادر</h2><p>لن يُعرض نص قرآني أو ترجمة أو تلاوة على أنها معتمدة قبل ربط مصدر موثق والتحقق من شروط استخدامه. اتجاه القبلة يحسب رياضيًا نحو الكعبة.</p>',languages:'<h2>اللغات والترجمات</h2><p>البنية تفصل لغة الواجهة عن ترجمة معاني القرآن. العربية والإنجليزية متاحتان للواجهة في هذه النسخة.</p>',export:'<h2>بياناتك</h2><button class="primary" id="downloadData">تصدير بياناتي</button><p class="muted">يمكن حفظ نسخة من تقدم الختمة والإعدادات دون إنشاء حساب.</p>'};$$('[data-modal]').forEach(b=>b.onclick=()=>{$('#modalContent').innerHTML=modalText[b.dataset.modal];modal.showModal();if(b.dataset.modal==='export')$('#downloadData').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='khatm-quran-data.json';a.click()}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');applyLang();
function openPage(id){$$('.page').forEach(p=>p.classList.remove('active'));const p=$('#'+id);if(p)p.classList.add('active');$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo(0,0);updateStatsPage()}
$$('.goto').forEach(b=>b.onclick=()=>openPage(b.dataset.target));
$('#continueBtn').onclick=()=>openPage('quran');
$('#surahGrid').innerHTML=surahs.map((s,i)=>'<button class="surah-item goto-surah" data-i="'+i+'"><b>'+(i+1)+'. '+s+'</b><small>سورة</small></button>').join('');$$('.goto-surah').forEach(b=>b.onclick=()=>{$('#surahSelect').selectedIndex=+b.dataset.i;openPage('quran')});
$('#quranSearch').addEventListener('input',e=>{let q=e.target.value.trim();$$('.surah-item').forEach((b,i)=>b.style.display=(!q||surahs[i].includes(q)||String(i+1)===q)?'block':'none')});
function updateStatsPage(){if(!$('#statRead'))return;$('#statRead').textContent=state.completed;$('#statLeft').textContent=TOTAL-state.completed;$('#statPct').textContent=Math.round(state.completed/TOTAL*100)+'%';$('#statDays').textContent=state.days;$('#historyProgress').textContent=state.completed+' / '+TOTAL+' صفحة'}
$('#settingsTheme').onclick=()=>$('#themeBtn').click();$('#settingsLang').onclick=()=>$('#langBtn').click();updateStatsPage();
// Production-ready prayer layer: public AlAdhan API; Quran content remains source-gated.
async function loadPrayerTimes(lat,lon){try{const ts=Math.floor(Date.now()/1000);const r=await fetch('https://api.aladhan.com/v1/timings/'+ts+'?latitude='+encodeURIComponent(lat)+'&longitude='+encodeURIComponent(lon)+'&method=4');if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json(),t=j.data.timings,n=['Fajr','Dhuhr','Asr','Maghrib','Isha'],ar=['الفجر','الظهر','العصر','المغرب','العشاء'];let box=$('#prayerStatus');box.className='prayer-times-grid';box.innerHTML=n.map((x,i)=>'<div class="prayer-time"><small>'+(state.lang==='ar'?ar[i]:x)+'</small><b>'+t[x]+'</b></div>').join('');const now=new Date(),mins=now.getHours()*60+now.getMinutes();let next=0;for(let i=0;i<n.length;i++){let [h,m]=t[n[i]].split(':').map(Number);if(h*60+m>mins){next=i;break}if(i===n.length-1)next=0}$('#nextPrayer').textContent=(state.lang==='ar'?ar[next]:n[next])+' • '+t[n[next]];if(j.data.date&&j.data.date.hijri){const h=j.data.date.hijri;box.insertAdjacentHTML('beforeend','<div class="prayer-time"><small>هجري</small><b>'+h.day+' '+h.month.ar+'</b></div>')}}catch(e){$('#prayerStatus').className='notice';$('#prayerStatus').textContent=state.lang==='ar'?'تعذر تحميل المواقيت الآن.':'Prayer times could not be loaded.'}}
function locateLive(){if(!navigator.geolocation){$('#prayerStatus').textContent='Geolocation unavailable';return}navigator.geolocation.getCurrentPosition(p=>{const lat=p.coords.latitude,lon=p.coords.longitude,deg=qibla(lat,lon);$('#qiblaDegrees').textContent=Math.round(deg)+'°';$('#needle').style.transform='rotate('+deg+'deg)';loadPrayerTimes(lat,lon)},()=>{$('#prayerStatus').className='notice';$('#prayerStatus').textContent=state.lang==='ar'?'لم يتم منح إذن الموقع.':'Location permission was not granted.'})}
$('#locateBtn').onclick=locateLive;$('#prayerLocate').onclick=locateLive;
$('#pageJumpBtn').onclick=()=>{const p=Math.max(1,Math.min(604,+$('#pageJump').value||1));state.readerPage=p;save();openPage('quran');$('#quranNotice').textContent=(state.lang==='ar'?'تم اختيار صفحة '+p+' — سيظهر نصها بعد ربط المصدر القرآني المعتمد.':'Page '+p+' selected — text will appear after the verified Quran source is connected.')};
// Interaction audit: every visible control now has an action or explicit availability feedback.
function showInfo(title,msg){$('#modalContent').innerHTML='<h2>'+title+'</h2><p>'+msg+'</p>';modal.showModal()}
$('.brand').onclick=e=>{e.preventDefault();openPage('home')};
function renderIndex(type){const grid=$('#surahGrid');$$('.tabs button').forEach(b=>b.classList.toggle('selected',b.dataset.index===type));if(type==='surahs'){grid.className='surah-grid';grid.innerHTML=surahs.map((s,i)=>'<button class="surah-item goto-surah" data-i="'+i+'"><b>'+(i+1)+'. '+s+'</b><small>سورة</small></button>').join('');$$('.goto-surah').forEach(b=>b.onclick=()=>{$('#surahSelect').selectedIndex=+b.dataset.i;openPage('quran')})}else if(type==='juz'){grid.className='number-grid';grid.innerHTML=Array.from({length:30},(_,i)=>'<button data-jump-page="'+(Math.floor(i*TOTAL/30)+1)+'"><b>الجزء '+(i+1)+'</b><small>انتقال تقريبي للصفحة</small></button>').join('');bindPageJumps()}else{grid.className='number-grid';grid.innerHTML=Array.from({length:604},(_,i)=>'<button data-jump-page="'+(i+1)+'">'+(i+1)+'</button>').join('');bindPageJumps()}}
function bindPageJumps(){$$('[data-jump-page]').forEach(b=>b.onclick=()=>{state.readerPage=+b.dataset.jumpPage;save();openPage('quran');$('#quranNotice').textContent='تم اختيار صفحة '+state.readerPage+' — سيظهر النص بعد ربط المصدر القرآني الموثق.'})}
$$('.tabs button').forEach(b=>b.onclick=()=>renderIndex(b.dataset.index));
$('#quranSearchBtn').onclick=()=>{renderIndex('surahs');$('#quranSearch').dispatchEvent(new Event('input'));$('#quranSearch').focus()};
$$('[data-open-index]').forEach(b=>b.onclick=()=>{const type=b.dataset.openIndex;if(type==='juz'||type==='pages'){openPage('discover');renderIndex(type)}else showInfo('فهرس الأحزاب','واجهة الأحزاب جاهزة، وسيتم ربط بدايات الأحزاب الدقيقة من بيانات المصحف الموثقة قبل تفعيل الانتقال.')});
$$('[data-reader-mode]').forEach(b=>b.onclick=()=>{$$('[data-reader-mode]').forEach(x=>x.classList.toggle('selected',x===b));state.readerMode=b.dataset.readerMode;save();$('.readerPlaceholder small').textContent=b.dataset.readerMode==='mushaf'?'وضع صفحات المصحف جاهز لبيانات الصفحات الموثقة.':'وضع الآيات جاهز للنص والترجمة وأدوات الآية.'});
$('#readerBookmarks').onclick=()=>openPage('bookmarks');$('#readerAudio').onclick=()=>openPage('audioPage');
$('#audioPlay').onclick=()=>showInfo('التلاوة','المشغل جاهز، ولن نشغّل ملفًا صوتيًا غير موثق. سيتم تفعيل التشغيل فور اعتماد مصدر التلاوات.');
$$('[data-audio]').forEach(b=>b.onclick=()=>showInfo('التلاوة','تم اختيار نمط التلاوة. يحتاج التشغيل الفعلي إلى مصدر صوت موثق قبل نشره.'));
$$('[data-trans]').forEach(b=>b.onclick=()=>{$$('[data-trans]').forEach(x=>x.classList.toggle('selected',x===b));state.translation=b.dataset.trans;save();showInfo('ترجمة المعاني','تم حفظ اختيار '+b.dataset.trans+'. سيظهر النص بعد اعتماد مصدر الترجمة وترخيصه.')});
$('#readerFontSize').value=state.readerFontSize||2;$('#readerFontSize').oninput=e=>{state.readerFontSize=+e.target.value;document.documentElement.style.setProperty('--reader-scale',(.85+state.readerFontSize*.15));save()};$('#readerFontSize').dispatchEvent(new Event('input'));
$('#reduceMotion').checked=!!state.reduceMotion;$('#reduceMotion').onchange=e=>{state.reduceMotion=e.target.checked;document.body.classList.toggle('reduce-motion',state.reduceMotion);save()};document.body.classList.toggle('reduce-motion',!!state.reduceMotion);
$$('[data-modal="export"]').forEach(b=>b.onclick=()=>{$('#modalContent').innerHTML='<h2>بياناتك</h2><div class="modal-actions"><button class="primary" id="downloadData">تصدير JSON</button><label class="outline import-label">استيراد JSON<input id="importData" type="file" accept="application/json" hidden></label></div><p class="muted">النسخة تشمل تقدم الختمة والإعدادات فقط.</p>';modal.showModal();$('#downloadData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='khatm-quran-data.json';a.click()};$('#importData').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(typeof data.days!=='number'||typeof data.completed!=='number')throw 0;state={...state,...data};save();modal.close();location.reload()}catch{showInfo('تعذر الاستيراد','الملف غير صالح أو لا يحتوي بيانات ختمة صحيحة.')}}});
renderIndex('surahs');
// Mobile-app continuity: 604-page reader position and page completion.
function syncReaderPosition(){state.readerPage=Math.max(1,Math.min(TOTAL,state.readerPage||Math.min(TOTAL,state.completed+1)));if($('#readerPageLabel'))$('#readerPageLabel').textContent=(state.lang==='ar'?'صفحة ':'Page ')+state.readerPage+(state.lang==='ar'?' من ':' of ')+TOTAL;save()}
$('#prevReaderPage').onclick=()=>{state.readerPage=Math.max(1,(state.readerPage||1)-1);syncReaderPosition()};$('#nextReaderPage').onclick=()=>{state.readerPage=Math.min(TOTAL,(state.readerPage||1)+1);syncReaderPosition()};$('#markReaderPage').onclick=()=>{syncReaderPosition();if(state.readerPage>state.completed)state.completed=state.readerPage;state.readerPage=Math.min(TOTAL,state.readerPage+1);save();render();updateStatsPage();syncReaderPosition();showInfo('تم تسجيل الصفحة','تم تحديث تقدم ختمتك محليًا على هذا الجهاز.')};
const oldOpenPage=openPage;openPage=function(id){oldOpenPage(id);if(id==='quran')syncReaderPosition()};syncReaderPosition();
// Full Quran reader — Tanzil Uthmani text, verbatim. 604-page Madinah metadata.
const AYAH_COUNTS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
let quranLines=[],quranPages=[],quranReady=false;
const QURAN_TEXT_URL='https://raw.githubusercontent.com/nuqayah/quran-text/master/quran-uthmani.txt';
function globalAyaIndex(sura,aya){let n=0;for(let i=0;i<sura-1;i++)n+=AYAH_COUNTS[i];return n+aya-1}
function locateGlobal(idx){let n=idx;for(let s=0;s<AYAH_COUNTS.length;s++){if(n<AYAH_COUNTS[s])return {sura:s+1,aya:n+1};n-=AYAH_COUNTS[s]}return {sura:114,aya:6}}
async function loadQuran(){if(quranReady)return true;try{const [tr,pr]=await Promise.all([fetch(QURAN_TEXT_URL,{cache:'force-cache'}),fetch('./quran-pages.json',{cache:'force-cache'})]);if(!tr.ok||!pr.ok)throw new Error('source');quranLines=(await tr.text()).trim().split(/\r?\n/);quranPages=await pr.json();if(quranLines.length!==6236||quranPages.length!==604)throw new Error('validation');quranReady=true;$('#quranLoading').hidden=true;renderQuranPage();return true}catch(e){$('#quranLoading').textContent='تعذر تحميل نص المصحف. تحقق من الاتصال ثم اضغط هنا لإعادة المحاولة.';$('#quranLoading').onclick=()=>{quranReady=false;loadQuran()};return false}}
function renderQuranPage(){if(!quranReady)return;syncReaderPosition();const p=state.readerPage||1,start=quranPages[p-1],next=quranPages[p];let a=globalAyaIndex(start.sura,start.aya),b=next?globalAyaIndex(next.sura,next.aya):6236;let out='',lastS=0;for(let i=a;i<b;i++){const pos=locateGlobal(i);if(pos.sura!==lastS){out+='<div class="sura-banner">سورة '+surahs[pos.sura-1]+'</div>';if(pos.aya===1&&pos.sura!==1&&pos.sura!==9)out+='<div class="bismillah">﷽</div>';lastS=pos.sura}out+='<button class="ayah" data-s="'+pos.sura+'" data-a="'+pos.aya+'"><span>'+quranLines[i]+'</span><i>﴿'+pos.aya+'﴾</i></button>'}$('#quranText').innerHTML=out;$('#surahSelect').selectedIndex=start.sura-1;$$('.ayah').forEach(el=>el.onclick=()=>openAyahActions(el.dataset.s,el.dataset.a,el.querySelector('span').textContent));}
function openAyahActions(s,a,t){$('#modalContent').innerHTML='<h2>'+surahs[s-1]+' • الآية '+a+'</h2><p class="ayah-modal">'+t+'</p><div class="modal-actions"><button class="primary" id="bookmarkAyah">♡ حفظ</button><button class="outline" id="copyAyah">نسخ</button><button class="outline" id="shareAyah">مشاركة</button><button class="outline" id="listenAyah">استماع</button></div>';modal.showModal();$('#bookmarkAyah').onclick=()=>{let x=JSON.parse(localStorage.getItem('khatm-bookmarks')||'[]');if(!x.some(v=>v.s==s&&v.a==a))x.push({s:+s,a:+a,t});localStorage.setItem('khatm-bookmarks',JSON.stringify(x));renderBookmarks();modal.close()};$('#copyAyah').onclick=()=>navigator.clipboard.writeText(t+' ﴿'+a+'﴾');$('#shareAyah').onclick=()=>navigator.share?navigator.share({title:'سورة '+surahs[s-1]+' - '+a,text:t}):navigator.clipboard.writeText(t);$('#listenAyah').onclick=()=>window.open('https://tanzil.net/#'+s+':'+a,'_blank','noopener')}
function renderBookmarks(){const host=$('#bookmarks .empty-state');if(!host)return;const x=JSON.parse(localStorage.getItem('khatm-bookmarks')||'[]');if(!x.length){host.innerHTML='<b>♡</b><h2>لا توجد علامات بعد</h2><p>اضغط على أي آية ثم اختر حفظ.</p><button class="primary goto" data-target="quran">افتح القرآن</button>';host.querySelector('.goto').onclick=()=>openPage('quran');return}host.innerHTML='<div class="bookmark-list">'+x.map((v,i)=>'<button data-bi="'+i+'"><b>'+surahs[v.s-1]+' • '+v.a+'</b><span>'+v.t+'</span></button>').join('')+'</div>';$$('[data-bi]').forEach(b=>b.onclick=()=>{const v=x[+b.dataset.bi];state.readerPage=findPageForAyah(v.s,v.a);save();openPage('quran');renderQuranPage()})}
function findPageForAyah(s,a){let found=1;for(let i=0;i<quranPages.length;i++){const p=quranPages[i];if(p.sura<s||(p.sura===s&&p.aya<=a))found=i+1;else break}return found}
$('#surahSelect').onchange=()=>{const s=$('#surahSelect').selectedIndex+1;state.readerPage=findPageForAyah(s,1);save();renderQuranPage()};
$('#prevReaderPage').onclick=()=>{state.readerPage=Math.max(1,(state.readerPage||1)-1);syncReaderPosition();renderQuranPage()};$('#nextReaderPage').onclick=()=>{state.readerPage=Math.min(TOTAL,(state.readerPage||1)+1);syncReaderPosition();renderQuranPage()};
const baseOpenPage=openPage;openPage=function(id){baseOpenPage(id);if(id==='quran')loadQuran().then(()=>renderQuranPage());if(id==='bookmarks')renderBookmarks()};
$('#quranSearchBtn').onclick=async()=>{await loadQuran();const q=$('#quranSearch').value.trim();if(!q)return;const normalized=q.replace(/[ًٌٍَُِّْـٰ]/g,'');const hits=[];for(let i=0;i<quranLines.length&&hits.length<50;i++){if(quranLines[i].replace(/[ًٌٍَُِّْـٰ]/g,'').includes(normalized)){const p=locateGlobal(i);hits.push({i,...p,t:quranLines[i]})}}const grid=$('#surahGrid');grid.className='search-results';grid.innerHTML=hits.length?hits.map(x=>'<button data-result="'+x.i+'"><b>'+surahs[x.sura-1]+' • '+x.aya+'</b><span>'+x.t+'</span></button>').join(''):'<div class="notice">لا توجد نتائج مطابقة.</div>';$$('[data-result]').forEach(b=>b.onclick=()=>{const x=locateGlobal(+b.dataset.result);state.readerPage=findPageForAyah(x.sura,x.aya);save();openPage('quran');renderQuranPage()})};
loadQuran();renderBookmarks();